drop sequence if exists bucket_seq;
create sequence bucket_seq start 1 increment 1;
drop sequence if exists category_seq;
create sequence category_seq start 1 increment 1;
drop sequence if exists order_details_seq;
create sequence order_details_seq start 1 increment 1;
drop sequence if exists order_seq;
create sequence order_seq start 1 increment 1;
drop sequence if exists product_seq;
create sequence product_seq start 1 increment 1;
drop sequence if exists user_seq;
create sequence user_seq start 1 increment 1;
drop sequence if exists products_images_seq;
create sequence products_images_seq start 1 increment 1;

drop table if exists bucket;
create table bucket
(
    id      int8 not null,
    user_id int8,
    primary key (id)
);

drop table if exists bucket_product;
create table bucket_product
(
    bucket_id  int8 not null,
    product_id int8 not null
);

drop table if exists category;
create table category
(
    id    int8 not null,
    title varchar(255),
    primary key (id)
);

drop table if exists order_details;
create table order_details
(
    id         int8 not null,
    amount     numeric(19, 2),
    price      numeric(19, 2),
    order_id   int8,
    product_id int8,
    primary key (id)
);

drop table if exists orders;
create table orders
(
    id      int8 not null,
    address varchar(255),
    created timestamp,
    status  varchar(255),
    sum     numeric(19, 2),
    updated timestamp,
    user_id int8,
    primary key (id)
);

drop table if exists product;
create table product
(
    id    int8 not null,
    price numeric(19, 2),
    title varchar(255),
    primary key (id)
);

drop table if exists product_category;
create table product_category
(
    product_id  int8 not null,
    category_id int8 not null
);

create table products_images
(
    id         int8 generated by default as identity,
    path       varchar(255),
    product_id int8,
    primary key (id)
);

drop table if exists users;
create table users
(
    id       int8    not null,
    archive  boolean not null,
    email    varchar(255),
    name     varchar(255),
    password varchar(255),
    role     varchar(255),
    primary key (id)
);
alter table if exists bucket
    add constraint FK327w43qqj7sg7250igsyxw7s3 foreign key (user_id) references users;
alter table if exists bucket_product
    add constraint FKfa2cy4lwdovqwwxpmvokyi96d foreign key (product_id) references product;
alter table if exists bucket_product
    add constraint FKq5o0ibigfi1slcwiouag7fhti foreign key (bucket_id) references bucket;
alter table if exists order_details
    add constraint FKjyu2qbqt8gnvno9oe9j2s2ldk foreign key (order_id) references orders;
alter table if exists order_details
    add constraint FKinivj2k1370kw224lavkm3rqm foreign key (product_id) references product;
alter table if exists orders
    add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users;
alter table if exists product_category
    add constraint FKkud35ls1d40wpjb5htpp14q4e foreign key (category_id) references category;
alter table if exists product_category
    add constraint FK2k3smhbruedlcrvu6clued06x foreign key (product_id) references product;
alter table if exists products_images add constraint FK1sv4otdj5wyajwcr2qrtuhmof foreign key (product_id) references product;